[build] 
    command = "sed -i 's/REACT_APP_AUTHORIZE_REDIRECT_PLACEHOLDER/$REACT_APP_AUTHORIZE_REDIRECT/g' netlify.toml && npm run build"

[[redirects]]
    from = "/authorize"
    to = 'REACT_APP_AUTHORIZE_REDIRECT_PLACEHOLDER'
    status = 200

